version: "3"

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: subwayhistory
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - 23306:3306
    subwayhistory-backend:
        image: htaehyun/subwayhistory-backend:latest
        ports:
            - 20001:8080
        depends_on:
            - db



