spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subwayhistory?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      example:
        subwayhistory: debug

seoul:
  api:
    host: http://openapi.seoul.go.kr:8088
    key: 67554e6f59786f67313031465764716f
